  url:
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 30m
  install:
    crds: CreateReplace
  chart:
    spec:
      chart: cilium
      version: "1.17.2"
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: kube-system
  values:
    cluster:
      name: self-hosted
    nodeinit:
      enabled: true
      reconfigureKubelet: "true"
      removeCbrBridge: "true"
    cni:
      binPath: "/home/kubernetes/bin"
    gke:
      enabled: true
    ipam:
      mode: "kubernetes"
    ipv4NativeRoutingCIDR: "10.20.0.0/14" # TODO: fetch this from a ConfigMap
  releaseName: cilium

