repos:

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.6.0
    hooks:
    - id: conventional-pre-commit
      stages: [commit-msg]
      args: []

  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.29
    hooks:
    - id: tflint
      stages: [pre-commit]
      args:
        - "--recursive"
